export enum ERR_CODE {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    TOO_MANY_REQUEST = 'TOO_MANY_REQUEST',

    // User
    USERNAME_IS_EXIST = 'USERNAME_IS_EXIST',
    USERNAME_OR_PASSWORD_NOT_MATCH = 'USERNAME_OR_PASSWORD_NOT_MATCH',
    ACCOUNT_NOT_ACTIVATED = 'ACCOUNT_NOT_ACTIVATED',
    INVALID_ACTIVATION_TOKEN = 'INVALID_ACTIVATION_TOKEN',
    ACTIVATION_TOKEN_EXPIRED = 'ACTIVATION_TOKEN_EXPIRED',
    INVALID_EXCHANGE_CODE = 'INVALID_EXCHANGE_CODE',
    EXCHANGE_CODE_EXPIRED = 'EXCHANGE_CODE_EXPIRED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',

    // Wallet
    INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
    WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
    INVALID_DEPOSIT_AMOUNT = 'INVALID_DEPOSIT_AMOUNT',
}
